//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alphaleonis.Win32.Vss.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alphaleonis.Win32.Vss.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during communication with writers..
        /// </summary>
        internal static string AnUnexpectedErrorOccurredDuringCommunicationWithWriters {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredDuringCommunicationWithWriters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected provider error. Check the event log for details..
        /// </summary>
        internal static string ExpectedProviderError {
            get {
                return ResourceManager.GetString("ExpectedProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML document. Check the event log for details..
        /// </summary>
        internal static string InvalidXMLDocumentCheckTheEventLogForDetails {
            get {
                return ResourceManager.GetString("InvalidXMLDocumentCheckTheEventLogForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System was unable to freeze the Distributed Transaction Coordinator (DTC) or the Kernel Transaction Manager (KTM).
        /// </summary>
        internal static string SystemWasUnableToFreezeDtcOrKtm {
            get {
                return ResourceManager.GetString("SystemWasUnableToFreezeDtcOrKtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of a shadow copy is already in progress..
        /// </summary>
        internal static string TheCreationOfAShadowCopyIsAlreadyInProgress {
            get {
                return ResourceManager.GetString("TheCreationOfAShadowCopyIsAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of volumes has already been added to the shadow copy set..
        /// </summary>
        internal static string TheMaximumNumberOfVolumesHasAlreadyBeenAddedToTheShadowCopySet {
            get {
                return ResourceManager.GetString("TheMaximumNumberOfVolumesHasAlreadyBeenAddedToTheShadowCopySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is not supported under the current context..
        /// </summary>
        internal static string TheOperationIsNotSupportedUnderTheCurrentContext {
            get {
                return ResourceManager.GetString("TheOperationIsNotSupportedUnderTheCurrentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider encountered an error that requires the user to restart the computer..
        /// </summary>
        internal static string TheProviderEncounteredAnErrorThatRequiresTheUserToRestartTheComputer {
            get {
                return ResourceManager.GetString("TheProviderEncounteredAnErrorThatRequiresTheUserToRestartTheComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider returned an unexpected error code..
        /// </summary>
        internal static string TheProviderReturnedAnUnexpectedErrorCode {
            get {
                return ResourceManager.GetString("TheProviderReturnedAnUnexpectedErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested identifier does not correspond to a registered provider..
        /// </summary>
        internal static string TheRequestedIdentifierDoesNotCorrespondToARegisteredProvider {
            get {
                return ResourceManager.GetString("TheRequestedIdentifierDoesNotCorrespondToARegisteredProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested object does not exist..
        /// </summary>
        internal static string TheRequestedObjectDoesNotExist {
            get {
                return ResourceManager.GetString("TheRequestedObjectDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested object was a duplicate..
        /// </summary>
        internal static string TheRequestedObjectWasADuplicate {
            get {
                return ResourceManager.GetString("TheRequestedObjectWasADuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system or provider has insufficient storage space. If possible delete any old or unnecessary persistent shadow copies and try again..
        /// </summary>
        internal static string TheSystemOrProviderHasInsufficientStorageSpace {
            get {
                return ResourceManager.GetString("TheSystemOrProviderHasInsufficientStorageSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system was unable to flush I/O writes. This can be a transient problem. It is recommended to wait ten minutes and try again, up to three times..
        /// </summary>
        internal static string TheSystemWasUnableToFlushIOWrites {
            get {
                return ResourceManager.GetString("TheSystemWasUnableToFlushIOWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system was unable to hold I/O writes. This can be a transient problem. It is recommended to wait ten minutes and try again, up to three times.
        /// </summary>
        internal static string TheSystemWasUnableToHoldIOWrites {
            get {
                return ResourceManager.GetString("TheSystemWasUnableToHoldIOWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume already has a revert in progress..
        /// </summary>
        internal static string TheVolumeAlreadyHasARevertInProgress {
            get {
                return ResourceManager.GetString("TheVolumeAlreadyHasARevertInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume does not support the requested operation, or no provider supports it..
        /// </summary>
        internal static string TheVolumeDoesNotSupportTheRequestedOperation {
            get {
                return ResourceManager.GetString("TheVolumeDoesNotSupportTheRequestedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume has already been added to the maximum number of shadow copy sets..
        /// </summary>
        internal static string TheVolumeHasAlreadyBeenAddedToTheMaximumNumberOfShadowCopySets {
            get {
                return ResourceManager.GetString("TheVolumeHasAlreadyBeenAddedToTheMaximumNumberOfShadowCopySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume is not supported by the specified provider..
        /// </summary>
        internal static string TheVolumeIsNotSupportedByTheSpecifiedProvider {
            get {
                return ResourceManager.GetString("TheVolumeIsNotSupportedByTheSpecifiedProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume was in use and could not be locked..
        /// </summary>
        internal static string TheVolumeWasInUseAndCouldNotBeLocked {
            get {
                return ResourceManager.GetString("TheVolumeWasInUseAndCouldNotBeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer infrastructure is not operating properly. Check that the Event Service and VSS have been started, and check for errors associated with those services in the error log..
        /// </summary>
        internal static string TheWriterInfrastructureIsNotOperatingProperly {
            get {
                return ResourceManager.GetString("TheWriterInfrastructureIsNotOperatingProperly", resourceCulture);
            }
        }
    }
}
