#ifndef ALPHAVSS_VERSION_H
#define ALPHAVSS_VERSION_H

#define STRINGIFY2(s)               #s
#define STRINGIFY(s)                STRINGIFY2(s)

#define ALPHAVSS_COPYRIGHT_STR      STRINGIFY(ALPHAVSS_COPYRIGHT)
#define ALPHAVSS_DESCRIPTION_STR    STRINGIFY(ALPHAVSS_DESCRIPTION)
#define ALPHAVSS_FILEVERSION_STR    STRINGIFY(ALPHAVSS_FILEVERSION)
#define ALPHAVSS_ASSEMBLYVERSION_STR    STRINGIFY(ALPHAVSS_ASSEMBLYVERSION)
#define ALPHAVSS_INFORMATIONALVERSION_STR    STRINGIFY(ALPHAVSS_INFORMATIONALVERSION)


#endif
