//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alphaleonis.Win32.Vss.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alphaleonis.Win32.Vss.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphaVSS requires at least Windows XP..
        /// </summary>
        public static string AlphaVSSRequiresAtLeastWindowsXP {
            get {
                return ResourceManager.GetString("AlphaVSSRequiresAtLeastWindowsXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another LUN resynchronization operation is already in progress..
        /// </summary>
        public static string AnotherLUNResynchronizationOperationIsAlreadyInProgress {
            get {
                return ResourceManager.GetString("AnotherLUNResynchronizationOperationIsAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. The error code is logged in the error log file..
        /// </summary>
        public static string AnUnexpectedErrorOccuredTheErrorCodeIsLogg {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccuredTheErrorCodeIsLogg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred during communication with writers..
        /// </summary>
        public static string AnUnexpectedErrorOccurredDuringCommunicationWithWriters {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredDuringCommunicationWithWriters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of snapshot failed. See inner exception for details. .
        /// </summary>
        public static string DeletionOfSnapshotFailedSeeInnerExceptionF {
            get {
                return ResourceManager.GetString("DeletionOfSnapshotFailedSeeInnerExceptionF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of snapshots failed.
        /// </summary>
        public static string DeletionOfSnapshotsFailed {
            get {
                return ResourceManager.GetString("DeletionOfSnapshotsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected provider error. Check the event log for details..
        /// </summary>
        public static string ExpectedProviderError {
            get {
                return ResourceManager.GetString("ExpectedProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detect architecture of running operating system..
        /// </summary>
        public static string FailedToDetectArchitectureOfRunningOperati {
            get {
                return ResourceManager.GetString("FailedToDetectArchitectureOfRunningOperati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IA64 architecture is not supported..
        /// </summary>
        public static string IA64ArchitectureIsNotSupported {
            get {
                return ResourceManager.GetString("IA64ArchitectureIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML document. Check the event log for details..
        /// </summary>
        public static string InvalidXMLDocumentCheckTheEventLogForDetails {
            get {
                return ResourceManager.GetString("InvalidXMLDocumentCheckTheEventLogForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of shadow copy storage areas has been added to the shadow copy source volume..
        /// </summary>
        public static string MaximumDiffAreaAssociationsReached {
            get {
                return ResourceManager.GetString("MaximumDiffAreaAssociationsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation is not supported on the current operating system..
        /// </summary>
        public static string RequestedOperationUnsupportedByOS {
            get {
                return ResourceManager.GetString("RequestedOperationUnsupportedByOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System was unable to freeze the Distributed Transaction Coordinator (DTC) or the Kernel Transaction Manager (KTM).
        /// </summary>
        public static string SystemWasUnableToFreezeDtcOrKtm {
            get {
                return ResourceManager.GetString("SystemWasUnableToFreezeDtcOrKtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of a shadow copy is already in progress..
        /// </summary>
        public static string TheCreationOfAShadowCopyIsAlreadyInProgress {
            get {
                return ResourceManager.GetString("TheCreationOfAShadowCopyIsAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of volumes has already been added to the shadow copy set..
        /// </summary>
        public static string TheMaximumNumberOfVolumesHasAlreadyBeenAddedToTheShadowCopySet {
            get {
                return ResourceManager.GetString("TheMaximumNumberOfVolumesHasAlreadyBeenAddedToTheShadowCopySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is not supported under the current context..
        /// </summary>
        public static string TheOperationIsNotSupportedUnderTheCurrentContext {
            get {
                return ResourceManager.GetString("TheOperationIsNotSupportedUnderTheCurrentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider encountered an error that requires the user to restart the computer..
        /// </summary>
        public static string TheProviderEncounteredAnErrorThatRequiresTheUserToRestartTheComputer {
            get {
                return ResourceManager.GetString("TheProviderEncounteredAnErrorThatRequiresTheUserToRestartTheComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider returned an unexpected error code..
        /// </summary>
        public static string TheProviderReturnedAnUnexpectedErrorCode {
            get {
                return ResourceManager.GetString("TheProviderReturnedAnUnexpectedErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested identifier does not correspond to a registered provider..
        /// </summary>
        public static string TheRequestedIdentifierDoesNotCorrespondToARegisteredProvider {
            get {
                return ResourceManager.GetString("TheRequestedIdentifierDoesNotCorrespondToARegisteredProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested object does not exist..
        /// </summary>
        public static string TheRequestedObjectDoesNotExist {
            get {
                return ResourceManager.GetString("TheRequestedObjectDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested object was a duplicate..
        /// </summary>
        public static string TheRequestedObjectWasADuplicate {
            get {
                return ResourceManager.GetString("TheRequestedObjectWasADuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system or provider has insufficient storage space. If possible delete any old or unnecessary persistent shadow copies and try again..
        /// </summary>
        public static string TheSystemOrProviderHasInsufficientStorageSpace {
            get {
                return ResourceManager.GetString("TheSystemOrProviderHasInsufficientStorageSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system was unable to flush I/O writes. This can be a transient problem. It is recommended to wait ten minutes and try again, up to three times..
        /// </summary>
        public static string TheSystemWasUnableToFlushIOWrites {
            get {
                return ResourceManager.GetString("TheSystemWasUnableToFlushIOWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system was unable to hold I/O writes. This can be a transient problem. It is recommended to wait ten minutes and try again, up to three times.
        /// </summary>
        public static string TheSystemWasUnableToHoldIOWrites {
            get {
                return ResourceManager.GetString("TheSystemWasUnableToHoldIOWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume already has a revert in progress..
        /// </summary>
        public static string TheVolumeAlreadyHasARevertInProgress {
            get {
                return ResourceManager.GetString("TheVolumeAlreadyHasARevertInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume does not support the requested operation, or no provider supports it..
        /// </summary>
        public static string TheVolumeDoesNotSupportTheRequestedOperation {
            get {
                return ResourceManager.GetString("TheVolumeDoesNotSupportTheRequestedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume has already been added to the maximum number of shadow copy sets..
        /// </summary>
        public static string TheVolumeHasAlreadyBeenAddedToTheMaximumNumberOfShadowCopySets {
            get {
                return ResourceManager.GetString("TheVolumeHasAlreadyBeenAddedToTheMaximumNumberOfShadowCopySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume is not supported by the specified provider..
        /// </summary>
        public static string TheVolumeIsNotSupportedByTheSpecifiedProvider {
            get {
                return ResourceManager.GetString("TheVolumeIsNotSupportedByTheSpecifiedProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume was in use and could not be locked..
        /// </summary>
        public static string TheVolumeWasInUseAndCouldNotBeLocked {
            get {
                return ResourceManager.GetString("TheVolumeWasInUseAndCouldNotBeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VSS object was in an incorrect state for the requested operation..
        /// </summary>
        public static string TheVSSObjectWasInAnIncorrectStateForTheRequestedOperation {
            get {
                return ResourceManager.GetString("TheVSSObjectWasInAnIncorrectStateForTheRequestedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer infrastructure is not operating properly. Check that the Event Service and VSS have been started, and check for errors associated with those services in the error log..
        /// </summary>
        public static string TheWriterInfrastructureIsNotOperatingProperly {
            get {
                return ResourceManager.GetString("TheWriterInfrastructureIsNotOperatingProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer is not responding..
        /// </summary>
        public static string TheWriterIsNotResponding {
            get {
                return ResourceManager.GetString("TheWriterIsNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires {0}{1}. Detected operating system was: {2}{3}..
        /// </summary>
        public static string ThisOperationRequires01DetectedOperatingSystemWas23 {
            get {
                return ResourceManager.GetString("ThisOperationRequires01DetectedOperatingSystemWas23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires {0}{1} or later. Detected operating system was: {2}{3}..
        /// </summary>
        public static string ThisOperationRequires01OrLaterDetectedOperatingSystemWas23 {
            get {
                return ResourceManager.GetString("ThisOperationRequires01OrLaterDetectedOperatingSystemWas23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires {0}. Detected operating system was: {1}..
        /// </summary>
        public static string ThisOperationRequires0DetectedOperatingSystemWas1 {
            get {
                return ResourceManager.GetString("ThisOperationRequires0DetectedOperatingSystemWas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires {0} or later. Detected operating system was: {1}..
        /// </summary>
        public static string ThisOperationRequires0OrLaterDetectedOperatingSystemWas1 {
            get {
                return ResourceManager.GetString("ThisOperationRequires0OrLaterDetectedOperatingSystemWas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires {0} with at least Service Pack {1}. Detected operating system was: {2}{3}..
        /// </summary>
        public static string ThisOperationRequires0WithAtLeastServicePack1DetectedOperatingSystemWas23 {
            get {
                return ResourceManager.GetString("ThisOperationRequires0WithAtLeastServicePack1DetectedOperatingSystemWas23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation requires {0} with at least Service Pack {1}, or {2} with at least service pack {3}. Detected operating system was: {4}{5}..
        /// </summary>
        public static string ThisOperationRequires0WithAtLeastServicePack1Or2WithAtLeastServicePack3DetectedOperatingSystemWas45 {
            get {
                return ResourceManager.GetString("ThisOperationRequires0WithAtLeastServicePack1Or2WithAtLeastServicePack3DetectedOp" +
                        "eratingSystemWas45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of the hardware provider does not support this operation..
        /// </summary>
        public static string ThisVersionOfTheHardwareProviderDoesNotSupportThisOperation {
            get {
                return ResourceManager.GetString("ThisVersionOfTheHardwareProviderDoesNotSupportThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected system error..
        /// </summary>
        public static string UnexpectedSystemError {
            get {
                return ResourceManager.GetString("UnexpectedSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested method is not supported on the current operating system, or the loaded assembly is targeted for a different operating system than the one on which it is running..
        /// </summary>
        public static string UnsupportedOperatingSystemExceptionMessage {
            get {
                return ResourceManager.GetString("UnsupportedOperatingSystemExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MBR signature or GPT ID for one or more disks could not be set to the intended value. Check the Application event log for more information..
        /// </summary>
        public static string VssCannotRevertDiskIdExceptionMessage {
            get {
                return ResourceManager.GetString("VssCannotRevertDiskIdExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shadow copy contains only a subset of the volumes needed by the writer to correctly back up the application component..
        /// </summary>
        public static string VssInconsistentSnapshotWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssInconsistentSnapshotWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer operation failed because of an error that might recur if another shadow copy is created..
        /// </summary>
        public static string VssNonRetryableWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssNonRetryableWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer ran out of memory or other system resources..
        /// </summary>
        public static string VssOutOfResourcesExceptionMessage {
            get {
                return ResourceManager.GetString("VssOutOfResourcesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer is reporting one or more component-level errors..
        /// </summary>
        public static string VssPartialFailureWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssPartialFailureWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer failed due to an error that would likely not occur if the entire backup, restore, or shadow copy creation process was restarted.
        /// </summary>
        public static string VssRetryableWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssRetryableWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified snapshot specifies a shadow copy that does not exist in the Backup Components Document..
        /// </summary>
        public static string VssSnapshotNotInSetExceptionMessage {
            get {
                return ResourceManager.GetString("VssSnapshotNotInSetExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The writer operation failed because of a time-out between the Freeze and Thaw events..
        /// </summary>
        public static string VssTimeoutWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssTimeoutWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resynchronization destination contained a volume that was not explicitly included..
        /// </summary>
        public static string VssUnselectedVolumeExceptionMessage {
            get {
                return ResourceManager.GetString("VssUnselectedVolumeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer status is not available for one or more writers. A writer may have reached the maximum number of available backup and restore sessions..
        /// </summary>
        public static string VssWriterStatusNotAvailableExceptionMessage {
            get {
                return ResourceManager.GetString("VssWriterStatusNotAvailableExceptionMessage", resourceCulture);
            }
        }
    }
}
